--
-- OIL_DENSITY  (Table) 
--
--  Dependencies: 
--   OIL_DESC (Table)
--   ORGANIZATION (Table)
--   OIL_TANK (Table)
--
CREATE TABLE OIL_DENSITY
(
  ID         NUMBER(14)                             NULL,
  ORG_ID     NUMBER(14)                             NULL,
  TANK_ID    NUMBER(14)                             NULL,
  OIL_ID     NUMBER(14)                             NULL,
  TIME       VARCHAR2(23 BYTE)                      NULL,
  TEST_TEMP  NUMBER(5,2)                        DEFAULT 0                         NULL,
  VSL_DENS   NUMBER(5,1)                        DEFAULT 0                         NULL,
  STD_DENS   NUMBER(5,1)                            NULL,
  CONSTRAINT OILDENSITY_PK PRIMARY KEY (ID),
  CONSTRAINT TIME_UNIQUE UNIQUE (TIME),
  CONSTRAINT DENSITY_OIL_FK FOREIGN KEY (OIL_ID) 
    REFERENCES OIL_DESC (OIL_ID),
  CONSTRAINT DENSITY_ORG_FK FOREIGN KEY (ORG_ID) 
    REFERENCES ORGANIZATION (ORG_ID),
  CONSTRAINT DENSITY_TANK_FK FOREIGN KEY (TANK_ID) 
    REFERENCES OIL_TANK (TANK_ID)
)
LOGGING 
NOCACHE
NOPARALLEL;

COMMENT ON COLUMN OIL_DENSITY.ID IS 'Hello';

COMMENT ON COLUMN OIL_DENSITY.ORG_ID IS '这个字段2的注释';

COMMENT ON COLUMN OIL_DENSITY.TANK_ID IS '这是字段3的注释';

COMMENT ON COLUMN OIL_DENSITY.OIL_ID IS '这是字段4的注释';

COMMENT ON COLUMN OIL_DENSITY.TIME IS '这是字段5的注释';

COMMENT ON COLUMN OIL_DENSITY.TEST_TEMP IS '这是字段6的注释';

COMMENT ON COLUMN OIL_DENSITY.VSL_DENS IS '这是字段7的注释';

COMMENT ON COLUMN OIL_DENSITY.STD_DENS IS '这是字段8的注释';

