--
-- OIL_DENSITY  (Table) 
--
--  Dependencies: 
--   OIL_DESC (Table)
--   ORGANIZATION (Table)
--   OIL_TANK (Table)
--
CREATE TABLE OIL_DENSITY
(
  ID         NUMBER(14)                             NULL,
  ORG_ID     NUMBER(14)                             NULL,
  TANK_ID    NUMBER(14)                             NULL,
  OIL_ID     NUMBER(14)                             NULL,
  TIME       VARCHAR2(23 BYTE)                      NULL,
  TEST_TEMP  NUMBER(5,2)                        DEFAULT 0                         NULL,
  VSL_DENS   NUMBER(5,1)                        DEFAULT 0                         NULL,
  STD_DENS   NUMBER(5,1)                            NULL,
  CONSTRAINT OILDENSITY_PK PRIMARY KEY (ID),
  CONSTRAINT TIME_UNIQUE UNIQUE (TIME),
  CONSTRAINT DENSITY_OIL_FK FOREIGN KEY (OIL_ID) 
    REFERENCES OIL_DESC (OIL_ID),
  CONSTRAINT DENSITY_ORG_FK FOREIGN KEY (ORG_ID) 
    REFERENCES ORGANIZATION (ORG_ID),
  CONSTRAINT DENSITY_TANK_FK FOREIGN KEY (TANK_ID) 
    REFERENCES OIL_TANK (TANK_ID)
)
LOGGING 
NOCACHE
NOPARALLEL;

COMMENT ON COLUMN OIL_DENSITY.ID IS '唯一标识';

COMMENT ON COLUMN OIL_DENSITY.ORG_ID IS '单位ID';

COMMENT ON COLUMN OIL_DENSITY.TANK_ID IS '油罐标识';

COMMENT ON COLUMN OIL_DENSITY.OIL_ID IS '油品标识';

COMMENT ON COLUMN OIL_DENSITY.TIME IS '录入时间';

COMMENT ON COLUMN OIL_DENSITY.TEST_TEMP IS '测试温度';

COMMENT ON COLUMN OIL_DENSITY.VSL_DENS IS '视密度';

COMMENT ON COLUMN OIL_DENSITY.STD_DENS IS '标准密度';

